language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
  licenses:
    - android-sdk-license-5be876d5

branches:
  only:
    - master
    - android_develop

jdk: openjdk7

notifications:
  email: false

before_install:

  # use gradle 1.12
  - sudo rm -r /usr/local/gradle
  - curl -LO http://services.gradle.org/distributions/gradle-1.12-bin.zip
  - unzip -q gradle-1.12-bin.zip
  - sudo mv gradle-1.12 /usr/local/gradle

  # dependency : sdk-common (Common library)
  - git clone https://github.com/Project-SILPA/sdk-common.git

  # dependency : sdk-render (Render module)
  - git clone https://github.com/Project-SILPA/sdk-render.git
  
install: gradle clean build

script: gradle check
